<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CourseCardBasicProgrammingWithJavascript</name>
   <tag></tag>
   <elementGuidId>2a6adc81-6bb7-4cc0-b0c7-00c1bda30c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='containerCard']/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.imageHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c2bde514-30a2-4edd-8e7e-06df2bc2bd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/codingid-storage-bucket/storage/uploads/lp-course-image/1663321565ezgif.com-gif-maker (1).webp</value>
      <webElementGuid>19860173-00d2-4b7e-950f-4836a78e3ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageHeader</value>
      <webElementGuid>2d3925d8-b486-452e-ac43-873b67edbed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>course banner</value>
      <webElementGuid>34222cb8-0492-47e8-8ec1-265aebea58f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>course banner</value>
      <webElementGuid>0a31a479-f0f4-4ac1-b584-320f8861aad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loopevent&quot;)/li[@id=&quot;containerCard&quot;]/div[@class=&quot;cardOuter&quot;]/a[1]/div[@class=&quot;cardHeader&quot;]/img[@class=&quot;imageHeader&quot;]</value>
      <webElementGuid>3d23fec2-bb6e-4688-ab2b-034eb17fd634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='containerCard']/div/a/div/img</value>
      <webElementGuid>1eb0211c-00fa-464f-835a-ea7d0d1664ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='course banner']</value>
      <webElementGuid>7f7f9d19-c2a4-4247-a820-0bb065f64e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>be4b9ca0-21e8-4536-9e85-ec2b1c05d557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/codingid-storage-bucket/storage/uploads/lp-course-image/1663321565ezgif.com-gif-maker (1).webp' and @alt = 'course banner' and @title = 'course banner']</value>
      <webElementGuid>f9421d4b-0a31-422f-aec4-e826c110eb94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
