<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchbox_Course</name>
   <tag></tag>
   <elementGuidId>3fb69e37-a660-48c9-a404-06b3b2f1414e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchInputCourse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchInputCourse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10dd1c50-6874-4856-b484-581b3e782b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchInputCourse</value>
      <webElementGuid>196ad4ac-ca7a-4a6f-bc16-b07d2026fde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>2a7ba55f-7cb7-4759-9c08-256ebe482c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50672b51-53a9-4758-93d8-ec90e69d4d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control searchinput</value>
      <webElementGuid>d5a81e81-a658-4be7-8dcd-124164fd1a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>88438c86-7b9a-496f-a30a-cf0b57669d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchInputCourse&quot;)</value>
      <webElementGuid>d7512c87-ea2c-4f0e-ac1a-b5c89b49535a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchInputCourse']</value>
      <webElementGuid>a26dfb2d-910e-4adf-9905-30a407544474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerEventInner']/div/div/div[2]/input</value>
      <webElementGuid>f6d2e78a-4d0d-43c9-9fe7-f75f8f47dc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>dd665c2e-3079-4ae4-a3e0-0de4e1a6cbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchInputCourse' and @type = 'text' and @placeholder = '']</value>
      <webElementGuid>b505851d-65d9-4d1b-ac6f-cad112e4354d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
